### PR TITLE
Remove unused module, remove unused dependencies

### PR DESCRIPTION
**Pull request by snapshotpl**
I didn't update composer.locks and this need https://github.com/phpbenchmarks/zend/pull/1 to works better :)

### CODE REVIEW

**Comment by phpbenchmarks** [comment]
Hi, thanks for your PR !

Hello World is not impacted, but **REST Api is 19% faster** with your modifications !
I will merge it into `master`, and relaunch benchmarks as soon as `CakePHP 3.5` is over.

Thanks !

**Comment by snapshotpl** [comment]
@phpbenchmarks thanks! Waiting for merge. I cannot find phpbenchmarks:literal-route branch

**Comment by phpbenchmarks** [comment]
@snapshotpl You can't find it cause i first merge your code on `literal-route` branch, to test it.
After a discution with @fabpot, i decided to create a branch for a benchmark : `helloworld` and `restapi`, for now. Goal is to completly separate sour code for each benchmarks.

So, you can find your commit on this 2 new branches :
https://github.com/phpbenchmarks/zend-3-0/commits/helloworld
https://github.com/phpbenchmarks/zend-3-0/commits/restapi

**Comment by snapshotpl** [comment]
@phpbenchmarks great. Did you relaunch benchmarks after my changes and apply results into main page?

**Comment by phpbenchmarks** [comment]
Not for now. I'm on a huge modification of website, who will be launched at the end of january.
I will relaunch Zend benchmarks soon, but results will be visible with this new version, not before.

**Comment by phpbenchmarks** [comment]
@snapshotpl Could you send me an email, at steevan.barboyon@gmail.com ? I will need your help for next Zend benchmarks :)

**Comment by info-droid** [comment]
@snapshotpl 

Zend Framework 3.0 benchmarks has been relaunched!
http://www.phpbenchmarks.com/en/benchmark/apache-bench/php-7.2/zend-framework-3.0.html

**+24% for REST Api**, due to route definition modifications.

Thanks !

**Comment by phpbenchmarks** [comment]
@snapshotpl 

Zend Framework 3.0 benchmarks has been relaunched!
http://www.phpbenchmarks.com/en/benchmark/apache-bench/php-7.2/zend-framework-3.0.html

**+24% for REST Api**, due to route definition modifications.

Thanks !

**Pull request merged**
